# Generated by Django 5.2.8 on 2025-11-12 16:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración Principal', help_text='Nombre de la configuración', max_length=100)),
                ('default_temperature', models.FloatField(default=18.0, help_text='Temperatura por defecto cuando no hay horarios activos (°C)', validators=[django.core.validators.MinValueValidator(15.0), django.core.validators.MaxValueValidator(25.0)])),
                ('hysteresis', models.FloatField(default=0.2, help_text='Diferencia de temperatura para evitar ciclos on/off constantes (°C)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.5)])),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo el sistema de calefacción?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Calefacción',
                'verbose_name_plural': 'Configuraciones de Calefacción',
            },
        ),
        migrations.CreateModel(
            name='HeatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_heating', models.BooleanField(help_text='¿Está encendida la calefacción?')),
                ('current_temperature', models.FloatField(blank=True, help_text='Temperatura actual (°C)', null=True)),
                ('target_temperature', models.FloatField(blank=True, help_text='Temperatura objetivo (°C)', null=True)),
                ('action_reason', models.CharField(default='automatic', help_text='Razón del cambio (schedule, manual, default, etc.)', max_length=100)),
                ('actuator_id', models.CharField(blank=True, help_text='ID del actuador', max_length=50, null=True)),
                ('wifi_signal', models.IntegerField(blank=True, help_text='Señal WiFi del actuador', null=True)),
                ('free_heap', models.BigIntegerField(blank=True, help_text='Memoria libre del actuador', null=True)),
                ('source', models.CharField(default='system', help_text='Origen del log', max_length=50)),
            ],
            options={
                'verbose_name': 'Log de Calefacción',
                'verbose_name_plural': 'Logs de Calefacción',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='heating_hea_timesta_fa3417_idx'), models.Index(fields=['is_heating', '-timestamp'], name='heating_hea_is_heat_6c6652_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeatingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del horario', max_length=100)),
                ('weekdays', models.CharField(default='0,1,2,3,4', help_text="Días de la semana separados por comas (ej: '0,1,2,3,4' para L-V)", max_length=20)),
                ('start_time', models.TimeField(help_text='Hora de inicio')),
                ('end_time', models.TimeField(help_text='Hora de fin')),
                ('target_temperature', models.FloatField(help_text='Temperatura objetivo durante este horario (°C)', validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(30.0)])),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo este horario?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.ForeignKey(blank=True, help_text='Configuración asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='heating.heatingsettings')),
            ],
            options={
                'verbose_name': 'Horario de Calefacción',
                'verbose_name_plural': 'Horarios de Calefacción',
                'ordering': ['start_time'],
            },
        ),
    ]
