# Generated by Django 5.2.8 on 2025-11-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatingschedule',
            name='settings',
        ),
    ]
