# Generated by Django 5.2.8 on 2025-11-12 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingsettings',
            name='default_temperature',
            field=models.FloatField(default=18.0, help_text='Temperatura por defecto cuando no hay horarios activos (°C)', validators=[django.core.validators.MinValueValidator(15.0), django.core.validators.MaxValueValidator(25.0)]),
        ),
        migrations.AlterField(
            model_name='heatingsettings',
            name='hysteresis',
            field=models.FloatField(default=0.5, help_text='Diferencia de temperatura para evitar ciclos on/off constantes (°C)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.5)]),
        ),
    ]
