# Generated by Django 5.2.7 on 2025-10-23 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatingcontrol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heatingschedule',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveIndex(
            model_name='heatinglog',
            name='heating_hea_timesta_66c47a_idx',
        ),
        migrations.RemoveIndex(
            model_name='heatinglog',
            name='heating_hea_control_ea4ddb_idx',
        ),
        migrations.RenameField(
            model_name='heatinglog',
            old_name='target_temperature',
            new_name='temperature',
        ),
        migrations.AlterUniqueTogether(
            name='heatingschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='heatingcontrol',
            name='manual_override',
        ),
        migrations.RemoveField(
            model_name='heatinglog',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='heatinglog',
            name='temperature_after',
        ),
        migrations.RemoveField(
            model_name='heatinglog',
            name='temperature_before',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='high_temperature',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='low_temperature',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='friday',
            field=models.BooleanField(default=False, verbose_name='Viernes'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='monday',
            field=models.BooleanField(default=False, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='saturday',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='sunday',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='thursday',
            field=models.BooleanField(default=False, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='tuesday',
            field=models.BooleanField(default=False, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='heatingschedule',
            name='wednesday',
            field=models.BooleanField(default=False, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='max_temperature',
            field=models.FloatField(default=20.0, help_text='Temperatura máxima en °C', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='min_temperature',
            field=models.FloatField(default=20.0, help_text='Temperatura mínima en °C', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heatingcontrol',
            name='status',
            field=models.CharField(choices=[('off', 'Apagado'), ('on', 'Encendido'), ('auto', 'Automático'), ('manual', 'Manual'), ('manual_on', 'Manual Encendido'), ('manual_off', 'Manual Apagado'), ('manual_temp', 'Manual Temperatura')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='heatinglog',
            name='action',
            field=models.CharField(choices=[('turn_on', 'Encender'), ('turn_off', 'Apagar'), ('temperature_change', 'Cambio de temperatura'), ('manual_override', 'Override manual'), ('schedule_change', 'Cambio de horario'), ('system_start', 'Inicio del sistema'), ('system_stop', 'Parada del sistema'), ('error', 'Error')], max_length=20),
        ),
        migrations.AlterField(
            model_name='heatinglog',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heatinglog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='heatingschedule',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True),
        ),
        migrations.AlterField(
            model_name='temperaturethreshold',
            name='hysteresis',
            field=models.FloatField(default=0.5, help_text='Histéresis en °C para evitar fluctuaciones', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='temperaturethreshold',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
