# Generated by Django 5.2.7 on 2025-10-29 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_alter_heatingcontrol_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del perfil', max_length=100)),
                ('profile_type', models.CharField(choices=[('normal', 'Normal'), ('vacation', 'Vacaciones'), ('night', 'Nocturno'), ('economy', 'Económico'), ('custom', 'Personalizado')], default='custom', help_text='Tipo de perfil', max_length=20)),
                ('min_temperature', models.FloatField(default=16.0, help_text='Temperatura mínima para protección (°C)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('default_comfort_temperature', models.FloatField(default=20.0, help_text='Temperatura de confort por defecto (°C)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(35)])),
                ('night_temperature', models.FloatField(default=17.0, help_text='Temperatura durante la noche (00:00-06:00)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('auto_activate_weekdays', models.BooleanField(default=True, help_text='Activar automáticamente en días laborables')),
                ('auto_activate_weekends', models.BooleanField(default=True, help_text='Activar automáticamente en fines de semana')),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='Perfil por defecto del sistema')),
                ('night_start_time', models.TimeField(default='23:00', help_text='Hora de inicio del modo nocturno')),
                ('night_end_time', models.TimeField(default='06:00', help_text='Hora de fin del modo nocturno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
