# Generated by Django 5.2.8 on 2026-04-15 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_remove_schedule_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del día', unique=True)),
                ('total_hours', models.FloatField(default=0.0, help_text='Horas totales de calefacción encendida ese día')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Uso Diario de Calefacción',
                'verbose_name_plural': 'Usos Diarios de Calefacción',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='heating_hea_date_88b817_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeatingMonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Año')),
                ('month', models.IntegerField(help_text='Mes (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_hours', models.FloatField(default=0.0, help_text='Horas totales de calefacción encendida ese mes')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Uso Mensual de Calefacción',
                'verbose_name_plural': 'Usos Mensuales de Calefacción',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
