# Generated by Django 5.2.7 on 2025-10-29 15:53

from django.db import migrations


def create_default_profiles(apps, schema_editor):
    """Crear perfiles de temperatura por defecto"""
    TemperatureProfile = apps.get_model('heating', 'TemperatureProfile')
    
    # Perfil Normal (por defecto)
    TemperatureProfile.objects.get_or_create(
        name="Normal",
        profile_type="normal",
        defaults={
            'min_temperature': 16.0,
            'default_comfort_temperature': 20.0,
            'night_temperature': 17.0,
            'night_start_time': '23:00',
            'night_end_time': '06:00',
            'auto_activate_weekdays': True,
            'auto_activate_weekends': True,
            'is_active': True,
            'is_default': True,
        }
    )
    
    # Perfil Vacaciones
    TemperatureProfile.objects.get_or_create(
        name="Vacaciones",
        profile_type="vacation",
        defaults={
            'min_temperature': 12.0,
            'default_comfort_temperature': 15.0,
            'night_temperature': 12.0,
            'night_start_time': '22:00',
            'night_end_time': '08:00',
            'auto_activate_weekdays': True,
            'auto_activate_weekends': True,
            'is_active': False,
            'is_default': False,
        }
    )
    
    # Perfil Económico
    TemperatureProfile.objects.get_or_create(
        name="Económico",
        profile_type="economy",
        defaults={
            'min_temperature': 15.0,
            'default_comfort_temperature': 18.0,
            'night_temperature': 16.0,
            'night_start_time': '23:30',
            'night_end_time': '06:30',
            'auto_activate_weekdays': True,
            'auto_activate_weekends': False,
            'is_active': False,
            'is_default': False,
        }
    )
    
    # Perfil Nocturno
    TemperatureProfile.objects.get_or_create(
        name="Solo Nocturno",
        profile_type="night",
        defaults={
            'min_temperature': 14.0,
            'default_comfort_temperature': 16.0,
            'night_temperature': 18.0,
            'night_start_time': '20:00',
            'night_end_time': '08:00',
            'auto_activate_weekdays': False,
            'auto_activate_weekends': True,
            'is_active': False,
            'is_default': False,
        }
    )


def reverse_create_default_profiles(apps, schema_editor):
    """Eliminar perfiles por defecto"""
    TemperatureProfile = apps.get_model('heating', 'TemperatureProfile')
    TemperatureProfile.objects.filter(
        name__in=["Normal", "Vacaciones", "Económico", "Solo Nocturno"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0003_temperatureprofile'),
    ]

    operations = [
        migrations.RunPython(
            create_default_profiles,
            reverse_create_default_profiles
        ),
    ]
