# Generated by Django 5.2.8 on 2025-11-12 17:12

from django.db import migrations, models


def migrate_day_of_week_to_weekdays(apps, schema_editor):
    """Convertir day_of_week individual a weekdays múltiples"""
    HeatingSchedule = apps.get_model('heating', 'HeatingSchedule')
    
    for schedule in HeatingSchedule.objects.all():
        if hasattr(schedule, 'day_of_week'):
            # Convertir día individual a string
            schedule.weekdays = str(schedule.day_of_week)
            schedule.save()


def reverse_weekdays_to_day_of_week(apps, schema_editor):
    """Conversión reversa (para rollback)"""
    HeatingSchedule = apps.get_model('heating', 'HeatingSchedule')
    
    for schedule in HeatingSchedule.objects.all():
        # Tomar el primer día de la lista
        days = [int(d.strip()) for d in schedule.weekdays.split(',') if d.strip().isdigit()]
        if days:
            schedule.day_of_week = days[0]
            schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0003_alter_heatingsettings_hysteresis'),
    ]

    operations = [
        # Agregar campo weekdays
        migrations.AddField(
            model_name='heatingschedule',
            name='weekdays',
            field=models.CharField(
                default='0,1,2,3,4',
                help_text='Días de la semana separados por comas (ej: "0,1,2,3,4" para L-V)',
                max_length=20
            ),
        ),
        
        # Migrar datos existentes
        migrations.RunPython(
            migrate_day_of_week_to_weekdays,
            reverse_weekdays_to_day_of_week
        ),
        
        # Remover campo antiguo
        migrations.RemoveField(
            model_name='heatingschedule',
            name='day_of_week',
        ),
    ]
