# Generated by Django 5.2.7 on 2025-10-29 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0004_auto_20251029_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración General', help_text='Nombre descriptivo', max_length=100)),
                ('minimum_temperature', models.FloatField(default=16.0, help_text='Temperatura mínima cuando no hay horarios activos (°C)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('hysteresis', models.FloatField(default=0.5, help_text='Histéresis en °C para evitar encendido/apagado frecuente', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(2.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Calefacción',
                'verbose_name_plural': 'Configuraciones de Calefacción',
            },
        ),
        migrations.DeleteModel(
            name='TemperatureProfile',
        ),
        migrations.DeleteModel(
            name='TemperatureThreshold',
        ),
    ]
