# Generated by Django 5.2.7 on 2025-10-22 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('refresh_interval', models.IntegerField(default=30, help_text='Intervalo de actualización en segundos')),
                ('temperature_unit', models.CharField(choices=[('C', '°C'), ('F', '°F')], default='C', max_length=2)),
                ('show_humidity', models.BooleanField(default=True)),
                ('show_heating_status', models.BooleanField(default=True)),
                ('data_retention_days', models.IntegerField(default=365, help_text='Días para mantener datos históricos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard configurations',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('sensor_offline', 'Sensor Offline'), ('temperature_high', 'Temperatura Alta'), ('temperature_low', 'Temperatura Baja'), ('heating_failure', 'Fallo de Calefacción'), ('system_error', 'Error del Sistema')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='dashboard_a_is_acti_a4ba2d_idx'), models.Index(fields=['created_at'], name='dashboard_a_created_fe9d01_idx')],
            },
        ),
    ]
