# Generated by Django 5.2.7 on 2025-10-22 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery level in percentage', null=True)),
            ],
            options={
                'verbose_name_plural': 'Sensor statuses',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(default='room_sensor', max_length=50)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='°C', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='Room', max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sensors_sen_timesta_8162d3_idx'), models.Index(fields=['sensor_id', 'sensor_type'], name='sensors_sen_sensor__5b8779_idx')],
            },
        ),
    ]
