# Generated by Django 5.2.8 on 2025-11-12 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(help_text='ID del sensor', max_length=50)),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humedad en %', null=True)),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Timestamp del ESP (millis)', null=True)),
                ('wifi_signal', models.IntegerField(blank=True, help_text='Fuerza de señal WiFi (dBm)', null=True)),
                ('free_heap', models.BigIntegerField(blank=True, help_text='Memoria libre en bytes', null=True)),
                ('sensor_error', models.BooleanField(default=False, help_text='Error en el sensor')),
                ('source', models.CharField(default='mqtt_bridge', help_text='Origen del dato', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento de recepción')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor_id', '-created_at'], name='sensors_sen_sensor__5f68a5_idx')],
            },
        ),
    ]
