# Generated by Django 5.2.8 on 2025-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['-created_at'], name='sensors_sen_created_aea84f_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['temperature', '-created_at'], name='sensors_sen_tempera_3cd047_idx'),
        ),
    ]
