# Generated by Django 5.2.8 on 2025-11-12 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_id', models.CharField(help_text='ID del actuador', max_length=50)),
                ('is_heating', models.BooleanField(default=False, help_text='¿Está encendida la calefacción?')),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Timestamp del ESP (millis)', null=True)),
                ('wifi_signal', models.IntegerField(blank=True, help_text='Fuerza de señal WiFi (dBm)', null=True)),
                ('free_heap', models.BigIntegerField(blank=True, help_text='Memoria libre en bytes', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura del actuador en °C', null=True)),
                ('source', models.CharField(default='mqtt_bridge', help_text='Origen del dato', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento de recepción')),
            ],
            options={
                'verbose_name': 'Estado de Actuador',
                'verbose_name_plural': 'Estados de Actuadores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actuator_id', '-created_at'], name='actuators_a_actuato_c95dba_idx')],
            },
        ),
    ]
