# Generated by Django 5.2.8 on 2025-11-13 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_id', models.CharField(help_text='ID del actuador', max_length=50)),
                ('is_heating', models.BooleanField(default=False, help_text='Estado actual de calefacción')),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura actual en °C', null=True)),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Timestamp del ESP (millis)', null=True)),
                ('wifi_signal', models.IntegerField(blank=True, help_text='Señal WiFi (dBm)', null=True)),
                ('free_heap', models.BigIntegerField(blank=True, help_text='Memoria libre en bytes', null=True)),
                ('source', models.CharField(default='mqtt_bridge', help_text='Origen del dato', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento de recepción')),
                ('reading_type', models.CharField(choices=[('status_report', 'Reporte de Estado'), ('response_to_command', 'Respuesta a Comando'), ('periodic_reading', 'Lectura Periódica')], default='periodic_reading', help_text='Tipo de lectura para evitar bucles', max_length=20)),
            ],
            options={
                'verbose_name': 'Lectura de Actuador',
                'verbose_name_plural': 'Lecturas de Actuadores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actuator_id', '-created_at'], name='actuators_a_actuato_8d3257_idx'), models.Index(fields=['reading_type', '-created_at'], name='actuators_a_reading_1bf188_idx')],
            },
        ),
    ]
