# Generated by Django 5.2.8 on 2025-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actuators', '0002_actuatorreadings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActuatorReadings',
        ),
    ]
